# Generated by Django 4.2 on 2025-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2_products',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy'),
        ),
    ]
