# Generated by Django 4.2 on 2026-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_table2_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2_products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy/'),
        ),
    ]
