# Generated by Django 4.2 on 2026-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_table2_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2_products',
            name='type',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
