# Generated by Django 4.2 on 2026-01-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_table2_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2_products',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
