# Generated by Django 4.2 on 2026-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_table2_products_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table2_products',
            name='type',
        ),
        migrations.AddField(
            model_name='table2_products',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('doctor_prescription', 'Doctor Prescription')], default='regular', max_length=50),
        ),
    ]
