# Generated by Django 4.2 on 2026-01-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_table2_products_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table2_products',
            name='product_type',
            field=models.CharField(choices=[('Regular', 'regular'), ('Doctor Prescription', 'doctor prescription')], default='regular', max_length=50),
        ),
    ]
