# Generated by Django 4.2 on 2026-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_table2_products_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table3_orders',
            name='landmark',
        ),
        migrations.AddField(
            model_name='table3_orders',
            name='prescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table4_cart',
            name='prescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
