# Generated by Django 4.2 on 2026-02-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_table3_orders_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table4_cart',
            name='product_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
