# Generated by Django 4.2 on 2026-02-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_table4_cart_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table3_orders',
            name='product_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='table3_orders',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
