# Generated by Django 4.2 on 2026-02-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_table3_orders_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table4_cart',
            name='prescription',
        ),
    ]
