# Generated by Django 4.2 on 2026-02-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_table5_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='table5_ReportCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='myapp.table1_user')),
            ],
        ),
        migrations.DeleteModel(
            name='table5_UserReport',
        ),
    ]
